apiVersion: v1
kind: Service
metadata:
  namespace: gloo-system
  name: {{.ServiceName}}
  labels:
    app: {{.ServiceName}}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{.ServiceName}}